CREATE TABLE IF NOT EXISTS User(
	NAME TEXT PRIMARY KEY,
  	MONEY DECIMAL(10,2) NOT NULL,
  	IMAGE TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Card(
  	OWNER TEXT,
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
  	NAME TEXT UNIQUE NOT NULL,
  	DESCRIPTION TEXT NOT NULL,
  	TIER INTEGER NOT NULL CHECK (TIER <= 3),
  	FOREIGN KEY (OWNER) REFERENCES User(name)
);

CREATE TABLE IF NOT EXISTS CardType (
  	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CARD_ID INTEGER NOT NULL,
  	TYPES TEXT NOT NULL CHECK (TYPES IN ('nonchalant','god of programming', 'special'))
);

CREATE TABLE IF NOT EXISTS Achievements (
  	TITLE TEXT NOT NULL,
  	MESSAGE TEXT NOT NULL,
  	SYSTEM BOOL DEFAULT FALSE,
  	CARDID INTEGER,
  	TYPES INTEGER,
  	OWNER TEXT
);